### ISSUE TITLE
kanjize v1.3.0がインストールされるため、kanji2intがエラーになってしまう

### ISSUE THREAD

**Issue by asura** [Taka710/normalize-japanese-addresses-py#2]
## 現象

1. `$ pip install normalize-japanese-addresses==0.0.5`
   * このとき、`kanjize`の`1.3.0`がインストールされている
2. 先頭に`from normalize_japanese_addresses import normalize`を書いたスクリプトを実行する

### トレース情報

```
Traceback (most recent call last):
  File "/home/asura/m/test.py", line 1, in <module>
    from normalize_japanese_addresses import normalize
  File "/home/asura/m/.venv/lib/python3.10/site-packages/normalize_japanese_addresses/__init__.py", line 1, in <module>
    from .normalize import normalize
  File "/home/asura/m/.venv/lib/python3.10/site-packages/normalize_japanese_addresses/normalize.py", line 4, in <module>
    from .library.regex import getPrefectures, getPrefectureRegexes, getCityRegexes, replace_addr, normalizeTownName
  File "/home/asura/m/.venv/lib/python3.10/site-packages/normalize_japanese_addresses/library/regex.py", line 9, in <module>
    from .utils import kan2num
  File "/home/asura/m/.venv/lib/python3.10/site-packages/normalize_japanese_addresses/library/utils.py", line 3, in <module>
    from kanjize import kanji2int, int2kanji
ImportError: cannot import name 'kanji2int' from 'kanjize' (/home/asura/m/.venv/lib/python3.10/site-packages/kanjize/__init__.py)
```

## 原因と思われるもの

* `kanjize v1.3.0` にて `kanji2int` メソッドが[削除されている](https://github.com/nagataaaas/Kanjize/releases/tag/publish)
* `setup.py`にて`kanjize`のバージョンが指定されていない

## 対応案

下記のいずれかではないかと思います。

* 最新の`kanjize`に対応して、`kanji2int`を`kanji2number`に変更する
* `setup.py`にて`kanjize==1.0.0`などバージョンを指定しておく

パッケージングについて無知のため後者の対応が推奨される方法かどうかわかりません。

## バージョン情報

* python: 3.10.6
* pip: 22.0.2
* normalize-japanese-addresses: 0.0.5

**Comment by new-village** [comment]
私も同様の問題に気付いたので、`kanji2number` に対応する形でコード修正して Pull Request させていただきました。  
ご確認/マージいただけると幸いです。

**Comment by nakano-tomofumi** [comment]
@Taka710 

PyPIの方では、まだ同様のエラーが再現します。反映をお願いできないでしょうか？
