### ISSUE TITLE
おそらく pypi に登録されている version が古い

### ISSUE THREAD

**Issue by curoa** [Taka710/normalize-japanese-addresses-py#5]
`pip install normalize-japanese-addresses`
してから
```python
from normalize_japanese_addresses import normalize
print(normalize("札幌市西区24-2-2-3-3"))
# {'pref': '北海道', 'city': '札幌市西区', 'town': '二十四軒二条二丁目', 'addr': '3-3', 'lat': 43.074273, 'lng': 141.315099, 'level': 3}
```
を実行すると エラーが出ます。
しかし、 
`git clone git@github.com:curoa/normalize-japanese-addresses-py.git`
して実行するとエラーが出ず正常に実行できます。

おそらく pypi に登録されている version が古いのではないでしょうか？

---

pip 版でのエラー
```
Traceback (most recent call last):
  File "/home/blackcat/tmp/main.py", line 1, in <module>
    from normalize_japanese_addresses import normalize
  File "/home/blackcat/.pyenv/versions/3.11.7/lib/python3.11/site-packages/normalize_japanese_addresses/__init__.py", line 1, in <module>
    from .normalize import normalize
  File "/home/blackcat/.pyenv/versions/3.11.7/lib/python3.11/site-packages/normalize_japanese_addresses/normalize.py", line 5, in <module>
    from .library.regex import getPrefectures, getPrefectureRegexes, getCityRegexes, replace_addr, normalizeTownName, match_banchi_go_pattern
  File "/home/blackcat/.pyenv/versions/3.11.7/lib/python3.11/site-packages/normalize_japanese_addresses/library/regex.py", line 10, in <module>
    from .utils import kan2num, findKanjiNumbers
  File "/home/blackcat/.pyenv/versions/3.11.7/lib/python3.11/site-packages/normalize_japanese_addresses/library/utils.py", line 3, in <module>
    from kanjize import kanji2number, int2kanji
ImportError: cannot import name 'int2kanji' from 'kanjize' (/home/blackcat/.pyenv/versions/3.11.7/lib/python3.11/site-packages/kanjize/__init__.py)
```

git 版の正常実行の結果
```
False 札幌市西区
北海道 札幌市西区 {'town': '二十四軒二条二丁目'} 24-2-2-3-3 ^(([ニ二])十四|24)(([町丁])目?|番([町丁])|([(條|条)(條|条)])|軒|線|([之ノの])町?|地割|[-－﹣−‐⁃‑‒–—﹘―⎯⏤ーｰ─━])(([ニ二])|2)(([町丁])目?|番([町丁])|([(條|条)(條|条)])|軒|線|([之ノの])町?|地割|[-－﹣−‐⁃‑‒–—﹘―⎯⏤ーｰ─━])(([ニ二])|2)(([町丁])目?|番([町丁])|([(條|条)(條|条)])|軒|線|([之ノの])町?|地割|[-－﹣−‐⁃‑‒–—﹘―⎯⏤ーｰ─━]) 3-3
{'pref': '北海道', 'city': '札幌市西区', 'town': '二十四軒二条二丁目', 'addr': '3-3', 'lat': 43.074273, 'lng': 141.315099, 'level': 3}

```

---

ぜひ修正をお願いします。
とても便利で助かります。ありがとうございます。

**Comment by Taka710** [comment]
v0.0.7をpypiにアップしました。
